services:
  server:
    build:
      args:
        - VERSION=0.0.1-SNAPSHOT
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: MoroApp
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"

  db:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=MoroApp
    volumes:
      - db-data:/etc/data

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db_docker/db_data